### ISSUE TITLE
NoSuchMethodError exception from ReportBuilder.generateReports(ReportBuilder.java:107) with v8.2.4

### ISSUE THREAD

**Issue by anandbagmar** [damianszczepanik/cucumber-reporting#1223]
I am getting a `NoSuchMethodError` exception when generating the report with the latest version - 8.2.4. This same code is working with v8.4.2.

```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.reflect.Method org.apache.commons.lang3.reflect.MethodUtils.getMethodObject(java.lang.Class, java.lang.String, java.lang.Class[])'
        at org.apache.velocity.util.introspection.MethodMap.<clinit>(MethodMap.java:61)
        at org.apache.velocity.util.introspection.ClassMap$MethodCache.<init>(ClassMap.java:239)
        at org.apache.velocity.util.introspection.ClassMap$MethodCache.<init>(ClassMap.java:204)
        at org.apache.velocity.util.introspection.ClassMap.createMethodCache(ClassMap.java:127)
        at org.apache.velocity.util.introspection.ClassMap.<init>(ClassMap.java:88)
        at org.apache.velocity.util.introspection.IntrospectorCache.put(IntrospectorCache.java:168)
        at org.apache.velocity.util.introspection.IntrospectorBase.getMethod(IntrospectorBase.java:97)
        at org.apache.velocity.util.introspection.Introspector.getMethod(Introspector.java:94)
        at org.apache.velocity.util.introspection.UberspectImpl.getMethod(UberspectImpl.java:296)
        at org.apache.velocity.util.ClassUtils.getMethod(ClassUtils.java:203)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:174)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)
        at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:492)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
        at org.apache.velocity.runtime.directive.Parse.render(Parse.java:284)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
        at org.apache.velocity.Template.merge(Template.java:358)
        at org.apache.velocity.Template.merge(Template.java:262)
        at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:86)
        at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:67)
        at net.masterthought.cucumber.ReportBuilder.generatePages(ReportBuilder.java:189)
        at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:107)
        at com.znsio.teswiz.runner.CustomReports.generateReport(CustomReports.java:59)
        at com.znsio.teswiz.runner.Runner.run(Runner.java:78)
        at com.znsio.teswiz.runner.Runner.<init>(Runner.java:55)
        at com.znsio.teswiz.runner.Runner.main(Runner.java:204)

```

**Comment by damianszczepanik** [comment]
This https://github.com/damianszczepanik/cucumber-reporting/blob/master/pom.xml#L282 dependency is missing

**Comment by Reza-Nadaf** [comment]
Hi there,
I am also facing the same issue. I have tried adding velocity dependency as well as nets-buddy but still no luck and I am getting the error after the test successfully passes

**Comment by hiteshkaushik28** [comment]
Somehow its the same issue with me too. Did anyone find any fix?
@damianszczepanik I tried that exclusion but its not working. I am using java 21.

**Comment by damianszczepanik** [comment]
Latest version is different - check recent https://github.com/damianszczepanik/cucumber-reporting/tags
